name = "TestImages"
uuid = "5e47fb64-e119-507b-a336-dd2b206d9990"
version = "1.0.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
AxisArrays = "0.3"
FileIO = "1"
ZipFile = "0.7, 0.8"
julia = "1.3"

[extras]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
QuartzImageIO = "dca85d43-d64c-5e67-8c65-017450d5d020"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Colors", "FixedPointNumbers", "ImageMagick", "QuartzImageIO", "Test"]
